version: '3.4'

services:
  czfaker-api:
    build: .
    ports:
     - "4567:4567"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/healtz"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s
    restart: always
